export type RepoCategory =
  | "Web"
  | "Systems"
  | "Infrastructure"
  | "Data"
  | "AI"
  | "Developer tools";

export type Repository = {
  slug: string;
  name: string;
  owner: string;
  description: string;
  category: RepoCategory;
  language: string;
  difficulty: "Approachable" | "Intermediate" | "Advanced";
  concepts: readonly string[];
  github: string;
  accent: string;
  status: "live" | "planned";
};

export const categories = [
  "All",
  "Web",
  "Systems",
  "Infrastructure",
  "Data",
  "AI",
  "Developer tools",
] as const;

export const repositories: readonly Repository[] = [
  {
    slug: "herdr",
    name: "Herdr",
    owner: "herdrdev",
    description:
      "Herdr handles client requests, terminal sessions, saved state, and remote connections.",
    category: "Developer tools",
    language: "Rust",
    difficulty: "Intermediate",
    concepts: ["IPC", "PTY runtime", "Persistence"],
    github: "https://github.com/herdrdev/herdr",
    accent: "#b8ff65",
    status: "live",
  },
  {
    slug: "llama-cpp",
    name: "llama.cpp",
    owner: "ggml-org",
    description:
      "llama.cpp loads a model, tokenizes a prompt, runs its compute graph, and samples the next token.",
    category: "AI",
    language: "C / C++",
    difficulty: "Advanced",
    concepts: ["Inference", "GGUF", "Quantization"],
    github: "https://github.com/ggml-org/llama.cpp",
    accent: "#f3c86b",
    status: "live",
  },
  {
    slug: "beads",
    name: "Beads",
    owner: "gastownhall",
    description:
      "Beads turns CLI commands into issue graphs, syncs local state, and runs automation hooks.",
    category: "Developer tools",
    language: "Go",
    difficulty: "Intermediate",
    concepts: ["Issue graph", "Agent memory", "Sync"],
    github: "https://github.com/gastownhall/beads",
    accent: "#ff8f70",
    status: "live",
  },
  {
    slug: "unsloth",
    name: "Unsloth",
    owner: "unslothai",
    description:
      "Unsloth uses optimized kernels and adapters to load, train, and export fine-tuned models.",
    category: "AI",
    language: "Python",
    difficulty: "Advanced",
    concepts: ["Fine-tuning", "LoRA", "Kernels"],
    github: "https://github.com/unslothai/unsloth",
    accent: "#9b8cff",
    status: "live",
  },
  {
    slug: "cli-anything",
    name: "CLI-Anything",
    owner: "HKUDS",
    description:
      "CLI-Anything studies an app, designs its commands, builds a harness, and tests the result.",
    category: "Developer tools",
    language: "Python",
    difficulty: "Approachable",
    concepts: ["Agent harness", "CLI design", "Evaluation"],
    github: "https://github.com/HKUDS/CLI-Anything",
    accent: "#5ce0b2",
    status: "live",
  },
  {
    slug: "react",
    name: "React",
    owner: "facebook",
    description:
      "React schedules component updates, reconciles the tree, and sends changes to a renderer.",
    category: "Web",
    language: "JavaScript",
    difficulty: "Advanced",
    concepts: ["Fiber", "Scheduler", "Reconciliation"],
    github: "https://github.com/facebook/react",
    accent: "#69d9ff",
    status: "live",
  },
  {
    slug: "nextjs",
    name: "Next.js",
    owner: "vercel",
    description:
      "Next.js routes requests, renders React on the server, caches results, and bundles the app.",
    category: "Web",
    language: "TypeScript",
    difficulty: "Advanced",
    concepts: ["App Router", "RSC", "Caching"],
    github: "https://github.com/vercel/next.js",
    accent: "#f5f7f2",
    status: "live",
  },
  {
    slug: "vscode",
    name: "VS Code",
    owner: "microsoft",
    description:
      "The VS Code workbench, editor, language services, and extension host communicate across processes.",
    category: "Developer tools",
    language: "TypeScript",
    difficulty: "Advanced",
    concepts: ["Extension host", "IPC", "Workbench"],
    github: "https://github.com/microsoft/vscode",
    accent: "#53a9ff",
    status: "live",
  },
  {
    slug: "kubernetes",
    name: "Kubernetes",
    owner: "kubernetes",
    description:
      "Kubernetes turns desired state into work across its API server, controllers, scheduler, and kubelets.",
    category: "Infrastructure",
    language: "Go",
    difficulty: "Advanced",
    concepts: ["Control loops", "Scheduling", "Reconciliation"],
    github: "https://github.com/kubernetes/kubernetes",
    accent: "#6d92ff",
    status: "live",
  },
  {
    slug: "linux",
    name: "Linux",
    owner: "torvalds",
    description:
      "Linux handles a system call across the scheduler, memory, filesystems, network stack, and drivers.",
    category: "Systems",
    language: "C",
    difficulty: "Advanced",
    concepts: ["Syscalls", "Kernel", "Drivers"],
    github: "https://github.com/torvalds/linux",
    accent: "#ffd45b",
    status: "live",
  },
  {
    slug: "postgresql",
    name: "PostgreSQL",
    owner: "postgres",
    description:
      "PostgreSQL parses and plans SQL, executes it under MVCC, and records changes in storage and WAL.",
    category: "Data",
    language: "C",
    difficulty: "Advanced",
    concepts: ["Query planner", "MVCC", "WAL"],
    github: "https://github.com/postgres/postgres",
    accent: "#6eabde",
    status: "live",
  },
  {
    slug: "redis",
    name: "Redis",
    owner: "redis",
    description:
      "Redis uses one event loop to serve its data structures, persist changes, and replicate them.",
    category: "Data",
    language: "C",
    difficulty: "Intermediate",
    concepts: ["Event loop", "Replication", "Persistence"],
    github: "https://github.com/redis/redis",
    accent: "#ff6b62",
    status: "live",
  },
  {
    slug: "moby",
    name: "Moby",
    owner: "moby",
    description:
      "Moby creates containers from image layers and connects them to storage, networks, and a runtime.",
    category: "Infrastructure",
    language: "Go",
    difficulty: "Advanced",
    concepts: ["Containers", "Images", "Networking"],
    github: "https://github.com/moby/moby",
    accent: "#52c8ff",
    status: "live",
  },
  {
    slug: "git",
    name: "Git",
    owner: "git",
    description:
      "Git builds commits from its index and object graph, then stores and transfers them as packfiles.",
    category: "Developer tools",
    language: "C",
    difficulty: "Intermediate",
    concepts: ["Object graph", "Refs", "Packfiles"],
    github: "https://github.com/git/git",
    accent: "#f27b55",
    status: "live",
  },
  {
    slug: "rust",
    name: "Rust",
    owner: "rust-lang",
    description:
      "The Rust compiler parses code, checks its types and borrows, lowers it to MIR, and generates a binary.",
    category: "Systems",
    language: "Rust",
    difficulty: "Advanced",
    concepts: ["Compiler", "Borrow checker", "MIR"],
    github: "https://github.com/rust-lang/rust",
    accent: "#f0a36c",
    status: "live",
  },
  {
    slug: "go",
    name: "Go",
    owner: "golang",
    description:
      "Go's compiler and toolchain produce code that runs on its scheduler, garbage collector, and standard library.",
    category: "Systems",
    language: "Go",
    difficulty: "Advanced",
    concepts: ["Goroutines", "GC", "Compiler"],
    github: "https://github.com/golang/go",
    accent: "#5fd5dc",
    status: "live",
  },
  {
    slug: "cpython",
    name: "CPython",
    owner: "python",
    description:
      "CPython turns source into bytecode, evaluates it, and manages Python objects in memory.",
    category: "Systems",
    language: "C / Python",
    difficulty: "Advanced",
    concepts: ["Interpreter", "Bytecode", "Object model"],
    github: "https://github.com/python/cpython",
    accent: "#ffd85a",
    status: "live",
  },
  {
    slug: "nodejs",
    name: "Node.js",
    owner: "nodejs",
    description:
      "Node.js connects JavaScript to native code, the event loop, workers, streams, and the network.",
    category: "Systems",
    language: "C++ / JavaScript",
    difficulty: "Advanced",
    concepts: ["Event loop", "V8", "libuv"],
    github: "https://github.com/nodejs/node",
    accent: "#78c878",
    status: "live",
  },
  {
    slug: "deno",
    name: "Deno",
    owner: "denoland",
    description:
      "Deno connects TypeScript tooling and web APIs to V8, Rust ops, and its permission checks.",
    category: "Systems",
    language: "Rust / TypeScript",
    difficulty: "Advanced",
    concepts: ["Runtime ops", "Permissions", "Web APIs"],
    github: "https://github.com/denoland/deno",
    accent: "#d5ff72",
    status: "live",
  },
  {
    slug: "supabase",
    name: "Supabase",
    owner: "supabase",
    description:
      "Supabase builds auth, realtime updates, storage, and APIs around PostgreSQL.",
    category: "Data",
    language: "TypeScript",
    difficulty: "Intermediate",
    concepts: ["Auth", "Realtime", "Storage"],
    github: "https://github.com/supabase/supabase",
    accent: "#4ee6a4",
    status: "live",
  },
  {
    slug: "grafana",
    name: "Grafana",
    owner: "grafana",
    description:
      "Grafana queries data through plugins, transforms the results, and feeds dashboards and alerts.",
    category: "Data",
    language: "Go / TypeScript",
    difficulty: "Advanced",
    concepts: ["Plugins", "Queries", "Alerting"],
    github: "https://github.com/grafana/grafana",
    accent: "#ff9d4d",
    status: "live",
  },
  {
    slug: "terraform",
    name: "Terraform",
    owner: "hashicorp",
    description:
      "Terraform turns configuration into a dependency graph, a plan, provider calls, and saved state.",
    category: "Infrastructure",
    language: "Go",
    difficulty: "Advanced",
    concepts: ["DAG", "Providers", "State"],
    github: "https://github.com/hashicorp/terraform",
    accent: "#a98cff",
    status: "live",
  },
  {
    slug: "home-assistant",
    name: "Home Assistant",
    owner: "home-assistant",
    description:
      "Home Assistant links integrations and device I/O to entity state, events, services, and automations.",
    category: "Infrastructure",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Event bus", "Integrations", "State"],
    github: "https://github.com/home-assistant/core",
    accent: "#4cc4ff",
    status: "live",
  },
  {
    slug: "pytorch",
    name: "PyTorch",
    owner: "pytorch",
    description:
      "PyTorch dispatches tensor operations, records autograd, compiles graphs, and runs across devices.",
    category: "AI",
    language: "Python / C++",
    difficulty: "Advanced",
    concepts: ["Autograd", "Dispatch", "Tensors"],
    github: "https://github.com/pytorch/pytorch",
    accent: "#ff7657",
    status: "live",
  },
  {
    slug: "tensorflow",
    name: "TensorFlow",
    owner: "tensorflow",
    description:
      "TensorFlow runs tensors eagerly or as graphs, selects kernels and devices, then optimizes and serves models.",
    category: "AI",
    language: "C++ / Python",
    difficulty: "Advanced",
    concepts: ["Graphs", "Kernels", "Devices"],
    github: "https://github.com/tensorflow/tensorflow",
    accent: "#ffaf4a",
    status: "live",
  },
  {
    slug: "ollama",
    name: "Ollama",
    owner: "ollama",
    description:
      "Follow a local model request through the API, scheduler, model runner, memory planning, and hardware backends.",
    category: "AI",
    language: "Go",
    difficulty: "Intermediate",
    concepts: ["Model serving", "Scheduling", "GPU backends"],
    github: "https://github.com/ollama/ollama",
    accent: "#8ed8ff",
    status: "live",
  },
  {
    slug: "transformers",
    name: "Transformers",
    owner: "huggingface",
    description:
      "Trace pretrained models from configuration and tokenization through generation, training, and framework integrations.",
    category: "AI",
    language: "Python",
    difficulty: "Advanced",
    concepts: ["Pretrained models", "Tokenization", "Generation"],
    github: "https://github.com/huggingface/transformers",
    accent: "#ffd65a",
    status: "live",
  },
  {
    slug: "vllm",
    name: "vLLM",
    owner: "vllm-project",
    description:
      "See requests move through continuous batching, paged KV-cache management, distributed workers, and GPU kernels.",
    category: "AI",
    language: "Python / CUDA",
    difficulty: "Advanced",
    concepts: ["Continuous batching", "PagedAttention", "KV cache"],
    github: "https://github.com/vllm-project/vllm",
    accent: "#b89cff",
    status: "live",
  },
  {
    slug: "scikit-learn",
    name: "scikit-learn",
    owner: "scikit-learn",
    description:
      "Learn how estimators, preprocessing, model selection, pipelines, and compiled numerical routines fit together.",
    category: "AI",
    language: "Python / Cython",
    difficulty: "Intermediate",
    concepts: ["Estimators", "Pipelines", "Model selection"],
    github: "https://github.com/scikit-learn/scikit-learn",
    accent: "#f39a4b",
    status: "live",
  },
  {
    slug: "keras",
    name: "Keras",
    owner: "keras-team",
    description:
      "Map high-level layers and models onto tracing, training loops, serialization, and multiple tensor backends.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Layers", "Training loops", "Multi-backend"],
    github: "https://github.com/keras-team/keras",
    accent: "#ff6f76",
    status: "live",
  },
  {
    slug: "milvus",
    name: "Milvus",
    owner: "milvus-io",
    description:
      "Trace vector writes and searches across coordinators, streaming data, distributed query nodes, and object storage.",
    category: "Data",
    language: "Go / C++",
    difficulty: "Advanced",
    concepts: ["Vector search", "Distributed storage", "Indexing"],
    github: "https://github.com/milvus-io/milvus",
    accent: "#36d7c4",
    status: "live",
  },
  {
    slug: "ray",
    name: "Ray",
    owner: "ray-project",
    description:
      "Follow distributed tasks and actors through drivers, schedulers, workers, the object store, and cluster control.",
    category: "Infrastructure",
    language: "Python / C++",
    difficulty: "Advanced",
    concepts: ["Distributed tasks", "Actors", "Object store"],
    github: "https://github.com/ray-project/ray",
    accent: "#62a7ff",
    status: "live",
  },
  {
    slug: "jax",
    name: "JAX",
    owner: "jax-ml",
    description:
      "See Python array programs transform through tracing, autodiff, batching, JIT compilation, and device execution.",
    category: "AI",
    language: "Python",
    difficulty: "Advanced",
    concepts: ["Autodiff", "JIT compilation", "XLA"],
    github: "https://github.com/jax-ml/jax",
    accent: "#65c7ef",
    status: "live",
  },
  {
    slug: "qdrant",
    name: "Qdrant",
    owner: "qdrant",
    description:
      "Explore vector ingestion and filtering through collections, segments, HNSW indexes, persistence, and consensus.",
    category: "Data",
    language: "Rust",
    difficulty: "Advanced",
    concepts: ["Vector database", "HNSW", "Consensus"],
    github: "https://github.com/qdrant/qdrant",
    accent: "#dc527d",
    status: "live",
  },
  {
    slug: "sglang",
    name: "SGLang",
    owner: "sgl-project",
    description:
      "Trace structured generation from its frontend language through scheduling, prefix caching, model workers, and kernels.",
    category: "AI",
    language: "Python / CUDA",
    difficulty: "Advanced",
    concepts: ["Structured generation", "Prefix caching", "Model serving"],
    github: "https://github.com/sgl-project/sglang",
    accent: "#a4e36b",
    status: "live",
  },
  {
    slug: "langchain",
    name: "LangChain",
    owner: "langchain-ai",
    description:
      "Follow an application from prompts and model calls through runnable composition, tools, agents, and tracing hooks.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Runnables", "Agents", "Tool calling"],
    github: "https://github.com/langchain-ai/langchain",
    accent: "#59d89f",
    status: "live",
  },
  {
    slug: "browser-use",
    name: "Browser Use",
    owner: "browser-use",
    description:
      "See an agent turn a goal into browser observations, model decisions, validated actions, and task history.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Browser agents", "Computer use", "Tool calling"],
    github: "https://github.com/browser-use/browser-use",
    accent: "#6ee7b7",
    status: "live",
  },
  {
    slug: "crewai",
    name: "CrewAI",
    owner: "crewAIInc",
    description:
      "Map collaborative agents from crew and task definitions through execution, tools, memory, and event handling.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Multi-agent systems", "Task orchestration", "Memory"],
    github: "https://github.com/crewAIInc/crewAI",
    accent: "#ff8c69",
    status: "live",
  },
  {
    slug: "dify",
    name: "Dify",
    owner: "langgenius",
    description:
      "Explore an AI application platform spanning visual workflows, model providers, retrieval, tools, and API serving.",
    category: "AI",
    language: "TypeScript / Python",
    difficulty: "Advanced",
    concepts: ["Visual workflows", "RAG", "Model providers"],
    github: "https://github.com/langgenius/dify",
    accent: "#7d8cff",
    status: "live",
  },
  {
    slug: "llama-index",
    name: "LlamaIndex",
    owner: "run-llama",
    description:
      "Trace external data through connectors, parsing, indexes, retrievers, query engines, and agent workflows.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Data connectors", "Retrieval", "Query engines"],
    github: "https://github.com/run-llama/llama_index",
    accent: "#c07cff",
    status: "live",
  },
  {
    slug: "n8n",
    name: "n8n",
    owner: "n8n-io",
    description:
      "Follow an automation from the visual editor into workflow execution, credentials, integrations, queues, and persistence.",
    category: "Developer tools",
    language: "TypeScript",
    difficulty: "Advanced",
    concepts: ["Workflow automation", "Integrations", "Execution engine"],
    github: "https://github.com/n8n-io/n8n",
    accent: "#ff6d5b",
    status: "live",
  },
  {
    slug: "openhands",
    name: "OpenHands",
    owner: "OpenHands",
    description:
      "See a software agent plan work, invoke tools in a sandboxed runtime, observe results, and manage sessions.",
    category: "Developer tools",
    language: "Python / TypeScript",
    difficulty: "Advanced",
    concepts: ["Coding agents", "Sandboxing", "Tool execution"],
    github: "https://github.com/OpenHands/OpenHands",
    accent: "#4fc3b3",
    status: "live",
  },
  {
    slug: "cline",
    name: "Cline",
    owner: "cline",
    description:
      "Trace an editor task through model messages, context gathering, tool approval, terminal work, and file changes.",
    category: "Developer tools",
    language: "TypeScript",
    difficulty: "Advanced",
    concepts: ["Coding agents", "Editor extensions", "Tool approval"],
    github: "https://github.com/cline/cline",
    accent: "#61b5ff",
    status: "live",
  },
  {
    slug: "comfyui",
    name: "ComfyUI",
    owner: "Comfy-Org",
    description:
      "Follow a node graph from the browser through prompt validation, execution scheduling, model loading, and image output.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Node graphs", "Diffusion", "Model loading"],
    github: "https://github.com/Comfy-Org/ComfyUI",
    accent: "#ef7bc9",
    status: "live",
  },
  {
    slug: "whisper",
    name: "Whisper",
    owner: "openai",
    description:
      "Trace audio through log-Mel preprocessing, the encoder-decoder Transformer, language detection, and timestamp decoding.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Speech recognition", "Audio features", "Decoding"],
    github: "https://github.com/openai/whisper",
    accent: "#86e36f",
    status: "live",
  },
] as const;

export const repositoryBySlug = (slug: string) =>
  repositories.find((repository) => repository.slug === slug);

if (
  new Set(repositories.map(({ slug }) => slug)).size !== repositories.length
) {
  throw new Error("Repository catalog has duplicate slugs");
}
