export type RepoCategory =
  | "Web"
  | "Systems"
  | "Infrastructure"
  | "Data"
  | "AI"
  | "Developer tools";

export type Repository = {
  slug: string;
  name: string;
  owner: string;
  description: string;
  category: RepoCategory;
  language: string;
  difficulty: "Approachable" | "Intermediate" | "Advanced";
  concepts: readonly string[];
  github: string;
  stars: number;
  accent: string;
  status: "live" | "planned";
};

export type RepositorySort = "popular" | "approachable" | "name";

export const categories = [
  "All",
  "Web",
  "Systems",
  "Infrastructure",
  "Data",
  "AI",
  "Developer tools",
] as const;

export const repositories: readonly Repository[] = [
  {
    slug: "herdr",
    name: "Herdr",
    owner: "herdrdev",
    description:
      "Herdr handles client requests, terminal sessions, saved state, and remote connections.",
    category: "Developer tools",
    language: "Rust",
    difficulty: "Intermediate",
    concepts: ["IPC", "PTY runtime", "Persistence"],
    github: "https://github.com/herdrdev/herdr",
    stars: 29_674,
    accent: "#b8ff65",
    status: "live",
  },
  {
    slug: "llama-cpp",
    name: "llama.cpp",
    owner: "ggml-org",
    description:
      "llama.cpp loads a model, tokenizes a prompt, runs its compute graph, and samples the next token.",
    category: "AI",
    language: "C / C++",
    difficulty: "Advanced",
    concepts: ["Inference", "GGUF", "Quantization"],
    github: "https://github.com/ggml-org/llama.cpp",
    stars: 124_130,
    accent: "#f3c86b",
    status: "live",
  },
  {
    slug: "beads",
    name: "Beads",
    owner: "gastownhall",
    description:
      "Beads turns CLI commands into issue graphs, syncs local state, and runs automation hooks.",
    category: "Developer tools",
    language: "Go",
    difficulty: "Intermediate",
    concepts: ["Issue graph", "Agent memory", "Sync"],
    github: "https://github.com/gastownhall/beads",
    stars: 26_359,
    accent: "#ff8f70",
    status: "live",
  },
  {
    slug: "unsloth",
    name: "Unsloth",
    owner: "unslothai",
    description:
      "Unsloth uses optimized kernels and adapters to load, train, and export fine-tuned models.",
    category: "AI",
    language: "Python",
    difficulty: "Advanced",
    concepts: ["Fine-tuning", "LoRA", "Kernels"],
    github: "https://github.com/unslothai/unsloth",
    stars: 72_355,
    accent: "#9b8cff",
    status: "live",
  },
  {
    slug: "cli-anything",
    name: "CLI-Anything",
    owner: "HKUDS",
    description:
      "CLI-Anything studies an app, designs its commands, builds a harness, and tests the result.",
    category: "Developer tools",
    language: "Python",
    difficulty: "Approachable",
    concepts: ["Agent harness", "CLI design", "Evaluation"],
    github: "https://github.com/HKUDS/CLI-Anything",
    stars: 47_586,
    accent: "#5ce0b2",
    status: "live",
  },
  {
    slug: "react",
    name: "React",
    owner: "facebook",
    description:
      "React schedules component updates, reconciles the tree, and sends changes to a renderer.",
    category: "Web",
    language: "JavaScript",
    difficulty: "Advanced",
    concepts: ["Fiber", "Scheduler", "Reconciliation"],
    github: "https://github.com/facebook/react",
    stars: 247_272,
    accent: "#69d9ff",
    status: "live",
  },
  {
    slug: "nextjs",
    name: "Next.js",
    owner: "vercel",
    description:
      "Next.js routes requests, renders React on the server, caches results, and bundles the app.",
    category: "Web",
    language: "TypeScript",
    difficulty: "Advanced",
    concepts: ["App Router", "RSC", "Caching"],
    github: "https://github.com/vercel/next.js",
    stars: 141_799,
    accent: "#f5f7f2",
    status: "live",
  },
  {
    slug: "vscode",
    name: "VS Code",
    owner: "microsoft",
    description:
      "The VS Code workbench, editor, language services, and extension host communicate across processes.",
    category: "Developer tools",
    language: "TypeScript",
    difficulty: "Advanced",
    concepts: ["Extension host", "IPC", "Workbench"],
    github: "https://github.com/microsoft/vscode",
    stars: 188_771,
    accent: "#53a9ff",
    status: "live",
  },
  {
    slug: "kubernetes",
    name: "Kubernetes",
    owner: "kubernetes",
    description:
      "Kubernetes turns desired state into work across its API server, controllers, scheduler, and kubelets.",
    category: "Infrastructure",
    language: "Go",
    difficulty: "Advanced",
    concepts: ["Control loops", "Scheduling", "Reconciliation"],
    github: "https://github.com/kubernetes/kubernetes",
    stars: 124_509,
    accent: "#6d92ff",
    status: "live",
  },
  {
    slug: "linux",
    name: "Linux",
    owner: "torvalds",
    description:
      "Linux handles a system call across the scheduler, memory, filesystems, network stack, and drivers.",
    category: "Systems",
    language: "C",
    difficulty: "Advanced",
    concepts: ["Syscalls", "Kernel", "Drivers"],
    github: "https://github.com/torvalds/linux",
    stars: 243_015,
    accent: "#ffd45b",
    status: "live",
  },
  {
    slug: "postgresql",
    name: "PostgreSQL",
    owner: "postgres",
    description:
      "PostgreSQL parses and plans SQL, executes it under MVCC, and records changes in storage and WAL.",
    category: "Data",
    language: "C",
    difficulty: "Advanced",
    concepts: ["Query planner", "MVCC", "WAL"],
    github: "https://github.com/postgres/postgres",
    stars: 21_806,
    accent: "#6eabde",
    status: "live",
  },
  {
    slug: "redis",
    name: "Redis",
    owner: "redis",
    description:
      "Redis uses one event loop to serve its data structures, persist changes, and replicate them.",
    category: "Data",
    language: "C",
    difficulty: "Intermediate",
    concepts: ["Event loop", "Replication", "Persistence"],
    github: "https://github.com/redis/redis",
    stars: 76_028,
    accent: "#ff6b62",
    status: "live",
  },
  {
    slug: "moby",
    name: "Moby",
    owner: "moby",
    description:
      "Moby creates containers from image layers and connects them to storage, networks, and a runtime.",
    category: "Infrastructure",
    language: "Go",
    difficulty: "Advanced",
    concepts: ["Containers", "Images", "Networking"],
    github: "https://github.com/moby/moby",
    stars: 71_981,
    accent: "#52c8ff",
    status: "live",
  },
  {
    slug: "git",
    name: "Git",
    owner: "git",
    description:
      "Git builds commits from its index and object graph, then stores and transfers them as packfiles.",
    category: "Developer tools",
    language: "C",
    difficulty: "Intermediate",
    concepts: ["Object graph", "Refs", "Packfiles"],
    github: "https://github.com/git/git",
    stars: 62_596,
    accent: "#f27b55",
    status: "live",
  },
  {
    slug: "rust",
    name: "Rust",
    owner: "rust-lang",
    description:
      "The Rust compiler parses code, checks its types and borrows, lowers it to MIR, and generates a binary.",
    category: "Systems",
    language: "Rust",
    difficulty: "Advanced",
    concepts: ["Compiler", "Borrow checker", "MIR"],
    github: "https://github.com/rust-lang/rust",
    stars: 115_517,
    accent: "#f0a36c",
    status: "live",
  },
  {
    slug: "go",
    name: "Go",
    owner: "golang",
    description:
      "Go's compiler and toolchain produce code that runs on its scheduler, garbage collector, and standard library.",
    category: "Systems",
    language: "Go",
    difficulty: "Advanced",
    concepts: ["Goroutines", "GC", "Compiler"],
    github: "https://github.com/golang/go",
    stars: 135_800,
    accent: "#5fd5dc",
    status: "live",
  },
  {
    slug: "cpython",
    name: "CPython",
    owner: "python",
    description:
      "CPython turns source into bytecode, evaluates it, and manages Python objects in memory.",
    category: "Systems",
    language: "C / Python",
    difficulty: "Advanced",
    concepts: ["Interpreter", "Bytecode", "Object model"],
    github: "https://github.com/python/cpython",
    stars: 74_334,
    accent: "#ffd85a",
    status: "live",
  },
  {
    slug: "nodejs",
    name: "Node.js",
    owner: "nodejs",
    description:
      "Node.js connects JavaScript to native code, the event loop, workers, streams, and the network.",
    category: "Systems",
    language: "C++ / JavaScript",
    difficulty: "Advanced",
    concepts: ["Event loop", "V8", "libuv"],
    github: "https://github.com/nodejs/node",
    stars: 118_952,
    accent: "#78c878",
    status: "live",
  },
  {
    slug: "deno",
    name: "Deno",
    owner: "denoland",
    description:
      "Deno connects TypeScript tooling and web APIs to V8, Rust ops, and its permission checks.",
    category: "Systems",
    language: "Rust / TypeScript",
    difficulty: "Advanced",
    concepts: ["Runtime ops", "Permissions", "Web APIs"],
    github: "https://github.com/denoland/deno",
    stars: 108_249,
    accent: "#d5ff72",
    status: "live",
  },
  {
    slug: "supabase",
    name: "Supabase",
    owner: "supabase",
    description:
      "Supabase builds auth, realtime updates, storage, and APIs around PostgreSQL.",
    category: "Data",
    language: "TypeScript",
    difficulty: "Intermediate",
    concepts: ["Auth", "Realtime", "Storage"],
    github: "https://github.com/supabase/supabase",
    stars: 108_049,
    accent: "#4ee6a4",
    status: "live",
  },
  {
    slug: "grafana",
    name: "Grafana",
    owner: "grafana",
    description:
      "Grafana queries data through plugins, transforms the results, and feeds dashboards and alerts.",
    category: "Data",
    language: "Go / TypeScript",
    difficulty: "Advanced",
    concepts: ["Plugins", "Queries", "Alerting"],
    github: "https://github.com/grafana/grafana",
    stars: 76_294,
    accent: "#ff9d4d",
    status: "live",
  },
  {
    slug: "terraform",
    name: "Terraform",
    owner: "hashicorp",
    description:
      "Terraform turns configuration into a dependency graph, a plan, provider calls, and saved state.",
    category: "Infrastructure",
    language: "Go",
    difficulty: "Advanced",
    concepts: ["DAG", "Providers", "State"],
    github: "https://github.com/hashicorp/terraform",
    stars: 49_469,
    accent: "#a98cff",
    status: "live",
  },
  {
    slug: "home-assistant",
    name: "Home Assistant",
    owner: "home-assistant",
    description:
      "Home Assistant links integrations and device I/O to entity state, events, services, and automations.",
    category: "Infrastructure",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Event bus", "Integrations", "State"],
    github: "https://github.com/home-assistant/core",
    stars: 89_932,
    accent: "#4cc4ff",
    status: "live",
  },
  {
    slug: "pytorch",
    name: "PyTorch",
    owner: "pytorch",
    description:
      "PyTorch dispatches tensor operations, records autograd, compiles graphs, and runs across devices.",
    category: "AI",
    language: "Python / C++",
    difficulty: "Advanced",
    concepts: ["Autograd", "Dispatch", "Tensors"],
    github: "https://github.com/pytorch/pytorch",
    stars: 102_401,
    accent: "#ff7657",
    status: "live",
  },
  {
    slug: "tensorflow",
    name: "TensorFlow",
    owner: "tensorflow",
    description:
      "TensorFlow runs tensors eagerly or as graphs, selects kernels and devices, then optimizes and serves models.",
    category: "AI",
    language: "C++ / Python",
    difficulty: "Advanced",
    concepts: ["Graphs", "Kernels", "Devices"],
    github: "https://github.com/tensorflow/tensorflow",
    stars: 197_058,
    accent: "#ffaf4a",
    status: "live",
  },
  {
    slug: "ollama",
    name: "Ollama",
    owner: "ollama",
    description:
      "Follow a local model request through the API, scheduler, model runner, memory planning, and hardware backends.",
    category: "AI",
    language: "Go",
    difficulty: "Intermediate",
    concepts: ["Model serving", "Scheduling", "GPU backends"],
    github: "https://github.com/ollama/ollama",
    stars: 178_679,
    accent: "#8ed8ff",
    status: "live",
  },
  {
    slug: "transformers",
    name: "Transformers",
    owner: "huggingface",
    description:
      "Trace pretrained models from configuration and tokenization through generation, training, and framework integrations.",
    category: "AI",
    language: "Python",
    difficulty: "Advanced",
    concepts: ["Pretrained models", "Tokenization", "Generation"],
    github: "https://github.com/huggingface/transformers",
    stars: 164_145,
    accent: "#ffd65a",
    status: "live",
  },
  {
    slug: "vllm",
    name: "vLLM",
    owner: "vllm-project",
    description:
      "See requests move through continuous batching, paged KV-cache management, distributed workers, and GPU kernels.",
    category: "AI",
    language: "Python / CUDA",
    difficulty: "Advanced",
    concepts: ["Continuous batching", "PagedAttention", "KV cache"],
    github: "https://github.com/vllm-project/vllm",
    stars: 89_185,
    accent: "#b89cff",
    status: "live",
  },
  {
    slug: "scikit-learn",
    name: "scikit-learn",
    owner: "scikit-learn",
    description:
      "Learn how estimators, preprocessing, model selection, pipelines, and compiled numerical routines fit together.",
    category: "AI",
    language: "Python / Cython",
    difficulty: "Intermediate",
    concepts: ["Estimators", "Pipelines", "Model selection"],
    github: "https://github.com/scikit-learn/scikit-learn",
    stars: 66_960,
    accent: "#f39a4b",
    status: "live",
  },
  {
    slug: "keras",
    name: "Keras",
    owner: "keras-team",
    description:
      "Map high-level layers and models onto tracing, training loops, serialization, and multiple tensor backends.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Layers", "Training loops", "Multi-backend"],
    github: "https://github.com/keras-team/keras",
    stars: 64_232,
    accent: "#ff6f76",
    status: "live",
  },
  {
    slug: "milvus",
    name: "Milvus",
    owner: "milvus-io",
    description:
      "Trace vector writes and searches across coordinators, streaming data, distributed query nodes, and object storage.",
    category: "Data",
    language: "Go / C++",
    difficulty: "Advanced",
    concepts: ["Vector search", "Distributed storage", "Indexing"],
    github: "https://github.com/milvus-io/milvus",
    stars: 45_652,
    accent: "#36d7c4",
    status: "live",
  },
  {
    slug: "ray",
    name: "Ray",
    owner: "ray-project",
    description:
      "Follow distributed tasks and actors through drivers, schedulers, workers, the object store, and cluster control.",
    category: "Infrastructure",
    language: "Python / C++",
    difficulty: "Advanced",
    concepts: ["Distributed tasks", "Actors", "Object store"],
    github: "https://github.com/ray-project/ray",
    stars: 43_529,
    accent: "#62a7ff",
    status: "live",
  },
  {
    slug: "jax",
    name: "JAX",
    owner: "jax-ml",
    description:
      "See Python array programs transform through tracing, autodiff, batching, JIT compilation, and device execution.",
    category: "AI",
    language: "Python",
    difficulty: "Advanced",
    concepts: ["Autodiff", "JIT compilation", "XLA"],
    github: "https://github.com/jax-ml/jax",
    stars: 36_164,
    accent: "#65c7ef",
    status: "live",
  },
  {
    slug: "qdrant",
    name: "Qdrant",
    owner: "qdrant",
    description:
      "Explore vector ingestion and filtering through collections, segments, HNSW indexes, persistence, and consensus.",
    category: "Data",
    language: "Rust",
    difficulty: "Advanced",
    concepts: ["Vector database", "HNSW", "Consensus"],
    github: "https://github.com/qdrant/qdrant",
    stars: 34_003,
    accent: "#dc527d",
    status: "live",
  },
  {
    slug: "sglang",
    name: "SGLang",
    owner: "sgl-project",
    description:
      "Trace structured generation from its frontend language through scheduling, prefix caching, model workers, and kernels.",
    category: "AI",
    language: "Python / CUDA",
    difficulty: "Advanced",
    concepts: ["Structured generation", "Prefix caching", "Model serving"],
    github: "https://github.com/sgl-project/sglang",
    stars: 31_907,
    accent: "#a4e36b",
    status: "live",
  },
  {
    slug: "langchain",
    name: "LangChain",
    owner: "langchain-ai",
    description:
      "Follow an application from prompts and model calls through runnable composition, tools, agents, and tracing hooks.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Runnables", "Agents", "Tool calling"],
    github: "https://github.com/langchain-ai/langchain",
    stars: 144_337,
    accent: "#59d89f",
    status: "live",
  },
  {
    slug: "browser-use",
    name: "Browser Use",
    owner: "browser-use",
    description:
      "See an agent turn a goal into browser observations, model decisions, validated actions, and task history.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Browser agents", "Computer use", "Tool calling"],
    github: "https://github.com/browser-use/browser-use",
    stars: 109_399,
    accent: "#6ee7b7",
    status: "live",
  },
  {
    slug: "crewai",
    name: "CrewAI",
    owner: "crewAIInc",
    description:
      "Map collaborative agents from crew and task definitions through execution, tools, memory, and event handling.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Multi-agent systems", "Task orchestration", "Memory"],
    github: "https://github.com/crewAIInc/crewAI",
    stars: 57_158,
    accent: "#ff8c69",
    status: "live",
  },
  {
    slug: "dify",
    name: "Dify",
    owner: "langgenius",
    description:
      "Explore an AI application platform spanning visual workflows, model providers, retrieval, tools, and API serving.",
    category: "AI",
    language: "TypeScript / Python",
    difficulty: "Advanced",
    concepts: ["Visual workflows", "RAG", "Model providers"],
    github: "https://github.com/langgenius/dify",
    stars: 152_598,
    accent: "#7d8cff",
    status: "live",
  },
  {
    slug: "llama-index",
    name: "LlamaIndex",
    owner: "run-llama",
    description:
      "Trace external data through connectors, parsing, indexes, retrievers, query engines, and agent workflows.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Data connectors", "Retrieval", "Query engines"],
    github: "https://github.com/run-llama/llama_index",
    stars: 51_679,
    accent: "#c07cff",
    status: "live",
  },
  {
    slug: "n8n",
    name: "n8n",
    owner: "n8n-io",
    description:
      "Follow an automation from the visual editor into workflow execution, credentials, integrations, queues, and persistence.",
    category: "Developer tools",
    language: "TypeScript",
    difficulty: "Advanced",
    concepts: ["Workflow automation", "Integrations", "Execution engine"],
    github: "https://github.com/n8n-io/n8n",
    stars: 200_862,
    accent: "#ff6d5b",
    status: "live",
  },
  {
    slug: "openhands",
    name: "OpenHands",
    owner: "OpenHands",
    description:
      "See a software agent plan work, invoke tools in a sandboxed runtime, observe results, and manage sessions.",
    category: "Developer tools",
    language: "Python / TypeScript",
    difficulty: "Advanced",
    concepts: ["Coding agents", "Sandboxing", "Tool execution"],
    github: "https://github.com/OpenHands/OpenHands",
    stars: 84_193,
    accent: "#4fc3b3",
    status: "live",
  },
  {
    slug: "cline",
    name: "Cline",
    owner: "cline",
    description:
      "Trace an editor task through model messages, context gathering, tool approval, terminal work, and file changes.",
    category: "Developer tools",
    language: "TypeScript",
    difficulty: "Advanced",
    concepts: ["Coding agents", "Editor extensions", "Tool approval"],
    github: "https://github.com/cline/cline",
    stars: 66_272,
    accent: "#61b5ff",
    status: "live",
  },
  {
    slug: "comfyui",
    name: "ComfyUI",
    owner: "Comfy-Org",
    description:
      "Follow a node graph from the browser through prompt validation, execution scheduling, model loading, and image output.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Node graphs", "Diffusion", "Model loading"],
    github: "https://github.com/Comfy-Org/ComfyUI",
    stars: 127_912,
    accent: "#ef7bc9",
    status: "live",
  },
  {
    slug: "whisper",
    name: "Whisper",
    owner: "openai",
    description:
      "Trace audio through log-Mel preprocessing, the encoder-decoder Transformer, language detection, and timestamp decoding.",
    category: "AI",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Speech recognition", "Audio features", "Decoding"],
    github: "https://github.com/openai/whisper",
    stars: 107_369,
    accent: "#86e36f",
    status: "live",
  },
  {
    slug: "vue",
    name: "Vue.js",
    owner: "vuejs",
    description:
      "Vue compiles templates into render functions, tracks reactive dependencies, and patches the DOM as state changes.",
    category: "Web",
    language: "TypeScript",
    difficulty: "Intermediate",
    concepts: ["Reactivity", "Template compiler", "Virtual DOM"],
    github: "https://github.com/vuejs/core",
    stars: 54_188,
    accent: "#42b883",
    status: "live",
  },
  {
    slug: "svelte",
    name: "Svelte",
    owner: "sveltejs",
    description:
      "Svelte compiles components into JavaScript and CSS, then its runtime propagates state changes into the DOM.",
    category: "Web",
    language: "JavaScript",
    difficulty: "Intermediate",
    concepts: ["Compiler", "Runes", "DOM updates"],
    github: "https://github.com/sveltejs/svelte",
    stars: 87_972,
    accent: "#ff3e00",
    status: "live",
  },
  {
    slug: "django",
    name: "Django",
    owner: "django",
    description:
      "Django routes a request through middleware and views, persists data through its ORM, and builds the response.",
    category: "Web",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Request lifecycle", "ORM", "Middleware"],
    github: "https://github.com/django/django",
    stars: 88_430,
    accent: "#44b78b",
    status: "live",
  },
  {
    slug: "fastapi",
    name: "FastAPI",
    owner: "fastapi",
    description:
      "FastAPI turns typed route declarations into dependency resolution, validated requests, async handlers, and OpenAPI schemas.",
    category: "Web",
    language: "Python",
    difficulty: "Intermediate",
    concepts: ["Dependency injection", "ASGI", "Validation"],
    github: "https://github.com/fastapi/fastapi",
    stars: 101_626,
    accent: "#00c7a7",
    status: "live",
  },
  {
    slug: "bun",
    name: "Bun",
    owner: "oven-sh",
    description:
      "Bun combines a JavaScript runtime with native web APIs, a bundler, a package manager, and a test runner.",
    category: "Systems",
    language: "Rust / C++",
    difficulty: "Advanced",
    concepts: ["JavaScriptCore", "Event loop", "Toolchain"],
    github: "https://github.com/oven-sh/bun",
    stars: 95_428,
    accent: "#f7c873",
    status: "live",
  },
  {
    slug: "tauri",
    name: "Tauri",
    owner: "tauri-apps",
    description:
      "Tauri connects a webview to Rust commands through IPC while capabilities and plugins gate native access.",
    category: "Developer tools",
    language: "Rust",
    difficulty: "Intermediate",
    concepts: ["WebView", "IPC", "Capabilities"],
    github: "https://github.com/tauri-apps/tauri",
    stars: 110_260,
    accent: "#24c8db",
    status: "live",
  },
  {
    slug: "neovim",
    name: "Neovim",
    owner: "neovim",
    description:
      "Neovim runs editor state on an event loop and exposes it to UIs, remote clients, and Lua plugins through APIs.",
    category: "Developer tools",
    language: "C / Lua",
    difficulty: "Advanced",
    concepts: ["Event loop", "RPC", "Lua plugins"],
    github: "https://github.com/neovim/neovim",
    stars: 101_841,
    accent: "#81c45b",
    status: "live",
  },
  {
    slug: "godot",
    name: "Godot",
    owner: "godotengine",
    description:
      "Godot coordinates scene nodes, resources, signals, scripts, physics, and rendering inside its game loop.",
    category: "Developer tools",
    language: "C++",
    difficulty: "Advanced",
    concepts: ["Scene tree", "Signals", "Rendering"],
    github: "https://github.com/godotengine/godot",
    stars: 115_741,
    accent: "#65a5da",
    status: "live",
  },
  {
    slug: "prometheus",
    name: "Prometheus",
    owner: "prometheus",
    description:
      "Prometheus discovers targets, scrapes metrics into its time-series database, evaluates PromQL, and sends alerts.",
    category: "Data",
    language: "Go",
    difficulty: "Advanced",
    concepts: ["Scraping", "TSDB", "PromQL"],
    github: "https://github.com/prometheus/prometheus",
    stars: 65_713,
    accent: "#e6522c",
    status: "live",
  },
  {
    slug: "elasticsearch",
    name: "Elasticsearch",
    owner: "elastic",
    description:
      "Elasticsearch coordinates document writes and searches across shards backed by Lucene indexes and cluster state.",
    category: "Data",
    language: "Java",
    difficulty: "Advanced",
    concepts: ["Shards", "Lucene", "Cluster state"],
    github: "https://github.com/elastic/elasticsearch",
    stars: 77_835,
    accent: "#f04e98",
    status: "live",
  },
  {
    slug: "nushell",
    name: "Nushell",
    owner: "nushell",
    description:
      "Nushell parses commands into structured pipelines, streams typed values, and extends the shell through plugins.",
    category: "Developer tools",
    language: "Rust",
    difficulty: "Intermediate",
    concepts: ["Structured pipelines", "Shell parsing", "Plugins"],
    github: "https://github.com/nushell/nushell",
    stars: 40_272,
    accent: "#6dd7c7",
    status: "live",
  },
  {
    slug: "duckdb",
    name: "DuckDB",
    owner: "duckdb",
    description:
      "DuckDB parses and optimizes analytical SQL, executes vectorized operators, and reads columnar data in-process.",
    category: "Data",
    language: "C++",
    difficulty: "Advanced",
    concepts: ["Vectorized execution", "Query optimizer", "Columnar storage"],
    github: "https://github.com/duckdb/duckdb",
    stars: 40_262,
    accent: "#f4d65e",
    status: "live",
  },
  {
    slug: "ladybird",
    name: "Ladybird",
    owner: "LadybirdBrowser",
    description:
      "Ladybird turns URLs into network responses, DOM and CSS trees, rendered pixels, and JavaScript-driven updates.",
    category: "Web",
    language: "C++",
    difficulty: "Advanced",
    concepts: ["Browser engine", "HTML & CSS", "JavaScript runtime"],
    github: "https://github.com/LadybirdBrowser/ladybird",
    stars: 65_687,
    accent: "#f59e72",
    status: "live",
  },
  {
    slug: "tigerbeetle",
    name: "TigerBeetle",
    owner: "tigerbeetle",
    description:
      "TigerBeetle validates financial transfers, replicates them through consensus, and commits them to a deterministic storage engine.",
    category: "Data",
    language: "Zig",
    difficulty: "Advanced",
    concepts: ["Double-entry accounting", "Consensus", "Storage engine"],
    github: "https://github.com/tigerbeetle/tigerbeetle",
    stars: 16_796,
    accent: "#ff8a4c",
    status: "live",
  },
  {
    slug: "uv",
    name: "uv",
    owner: "astral-sh",
    description:
      "uv resolves Python dependencies, fetches and caches artifacts, builds environments, and runs project commands.",
    category: "Developer tools",
    language: "Rust",
    difficulty: "Intermediate",
    concepts: ["Dependency resolution", "Package cache", "Virtual environments"],
    github: "https://github.com/astral-sh/uv",
    stars: 88_781,
    accent: "#b197fc",
    status: "live",
  },
  {
    slug: "helix",
    name: "Helix",
    owner: "helix-editor",
    description:
      "Helix applies modal selections to rope-backed text, incrementally parses syntax, and coordinates language servers.",
    category: "Developer tools",
    language: "Rust",
    difficulty: "Intermediate",
    concepts: ["Rope editing", "Tree-sitter", "Language servers"],
    github: "https://github.com/helix-editor/helix",
    stars: 45_837,
    accent: "#c18cff",
    status: "live",
  },
  {
    slug: "tailscale",
    name: "Tailscale",
    owner: "tailscale",
    description:
      "Tailscale turns coordination state into peer routes, negotiates NAT traversal, and carries encrypted packets over WireGuard.",
    category: "Infrastructure",
    language: "Go",
    difficulty: "Advanced",
    concepts: ["WireGuard", "NAT traversal", "Mesh networking"],
    github: "https://github.com/tailscale/tailscale",
    stars: 35_242,
    accent: "#7ed9ff",
    status: "live",
  },
  {
    slug: "firecracker",
    name: "Firecracker",
    owner: "firecracker-microvm",
    description:
      "Firecracker converts API configuration into isolated KVM microVMs with a minimal device model and jailed runtime.",
    category: "Infrastructure",
    language: "Rust",
    difficulty: "Advanced",
    concepts: ["MicroVMs", "KVM", "Process isolation"],
    github: "https://github.com/firecracker-microvm/firecracker",
    stars: 36_095,
    accent: "#ff6b68",
    status: "live",
  },
  {
    slug: "pocketbase",
    name: "PocketBase",
    owner: "pocketbase",
    description:
      "PocketBase combines SQLite records, authentication, file storage, hooks, and realtime subscriptions in one server.",
    category: "Data",
    language: "Go",
    difficulty: "Intermediate",
    concepts: ["SQLite", "Realtime subscriptions", "Authentication"],
    github: "https://github.com/pocketbase/pocketbase",
    stars: 60_692,
    accent: "#62c4a5",
    status: "live",
  },
  {
    slug: "penpot",
    name: "Penpot",
    owner: "penpot",
    description:
      "Penpot synchronizes collaborative design changes, persists SVG-based documents, and renders them across browser and WASM boundaries.",
    category: "Web",
    language: "Clojure / ClojureScript",
    difficulty: "Advanced",
    concepts: ["Realtime collaboration", "SVG", "WASM rendering"],
    github: "https://github.com/penpot/penpot",
    stars: 58_686,
    accent: "#8b7cff",
    status: "live",
  },
  {
    slug: "x-algorithm",
    name: "X Algorithm",
    owner: "xai-org",
    description:
      "X Algorithm retrieves in-network and out-of-network posts, predicts viewer actions, filters them for safety, and blends the For You feed.",
    category: "AI",
    language: "Rust / Python",
    difficulty: "Advanced",
    concepts: ["Recommendation systems", "Candidate ranking", "Safety filtering"],
    github: "https://github.com/xai-org/x-algorithm",
    stars: 31_375,
    accent: "#f5f7f2",
    status: "live",
  },
] as const;

export const repositoryBySlug = (slug: string) =>
  repositories.find((repository) => repository.slug === slug);

const difficultyRank = { Approachable: 0, Intermediate: 1, Advanced: 2 };

export function sortRepositories(
  values: readonly Repository[],
  sort: RepositorySort,
) {
  return [...values].sort((left, right) => {
    if (sort === "name") return left.name.localeCompare(right.name);
    if (sort === "approachable") {
      return difficultyRank[left.difficulty] - difficultyRank[right.difficulty] || right.stars - left.stars;
    }
    return right.stars - left.stars;
  });
}

if (
  new Set(repositories.map(({ slug }) => slug)).size !== repositories.length
) {
  throw new Error("Repository catalog has duplicate slugs");
}
